### ISSUE TITLE
 cannot import name 'register_hstore_handler'

### ISSUE THREAD

**Issue by iMerica** [primal100/django_nosql#4]
Received the following error while installing this lib according to the docs.

```
root@4ae4fe029e54:/app# ./manage.py makemigrations
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 115, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/django_postgres_extensions/backends/postgresql/base.py", line 3, in <module>
    from .creation import DatabaseCreation
  File "/usr/local/lib/python3.6/site-packages/django_postgres_extensions/backends/postgresql/creation.py", line 1, in <module>
    from django.contrib.postgres.signals import register_hstore_handler
ImportError: cannot import name 'register_hstore_handler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/models.py", line 3, in <module>
    from django.contrib.sessions.base_session import (
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/base_session.py", line 30, in <module>
    class AbstractBaseSession(models.Model):
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 124, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 325, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/options.py", line 214, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/local/lib/python3.6/site-packages/django/db/__init__.py", line 33, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 211, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 134, in load_backend
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: 'django_postgres_extensions.backends.postgresql' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'
Error was: cannot import name 'register_hstore_handler'


```

**Comment by dchaplinsky** [comment]
Here is the patch:

```python
diff --git a/django_postgres_extensions/backends/postgresql/creation.py b/django_postgres_extensions/backends/postgresql/creation.py
index b60a005..0056cf3 100644
--- a/django_postgres_extensions/backends/postgresql/creation.py
+++ b/django_postgres_extensions/backends/postgresql/creation.py
@@ -1,4 +1,4 @@
-from django.contrib.postgres.signals import register_hstore_handler
+from django.contrib.postgres.signals import register_type_handlers
 from django.db.backends.postgresql.creation import DatabaseCreation as BaseDatabaseCreation
 from django.conf import settings

@@ -37,7 +37,7 @@ class DatabaseCreation(BaseDatabaseCreation):
         with self.connection.cursor() as cursor:
             for extension in ('hstore',):
                 cursor.execute("CREATE EXTENSION IF NOT EXISTS %s" % extension)
-        register_hstore_handler(self.connection)
+        register_type_handlers(self.connection)

         # We report migrate messages at one level lower than that requested.
         # This ensures we don't get flooded with messages during testing
```


unfortunately cannot test it as tests are broken (even once I've created superuser paul on my postgresql)

**Comment by primal100** [comment]
This library was originally developed with django 1.10. register_hstore_handler has been replaced with register_type_handlers. I'll need to work on upgrading it to work with Django 2.0.

**Comment by dchaplinsky** [comment]
Please!

raw sql is so much unpleasant when you are working with arrays.

**Comment by primal100** [comment]
Latest version (0.9.3) Works with django 2.0.2
